#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.y makemigrations --no-input
python manage.py migrate --no-input
python manage.py collectstatic --no-input
python manage.py createcachetable

if [ "$DJANGO_SUPERUSER_USERNAME" ]
then
    python manage.py createsuperuser \
        --noinput \
        --username $DJANGO_SUPERUSER_USERNAME \
        --email $DJANGO_SUPERUSER_USERNAME
fi

gunicorn server.wsgi:application --bind 0.0.0.0:8000
