#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --no-input
python manage.py collectstatic --no-input

if [ $FIRST_INIT == "True" ]; then
    export FIRST_INIT="False"

    read -p "### Create django superuser? (y/N) " decision
    if [ "$decision" == "Y" ] || [ "$decision" == "y" ]; then
        python manage.py createsuperuser
    fi
    
fi

gunicorn server.wsgi:application --bind 0.0.0.0:8000
